### ISSUE TITLE
Unknown type 39 & 40 - Horizontal Shades, tilt only

### ISSUE THREAD

**Issue by acolomba** [keybuk/homebridge-powerview#13]
I have Parkland blinds with only the tilting motion motorized. (They lift manually.) They show in the log like so:

```
[2018-12-24 21:12:26] [PowerView] *** Shade 44415 has unknown type 39, assuming roller ***
[2018-12-24 21:12:26] [PowerView] Set for 44415 { positions: { posKind1: 3, position1: 32768 } }
```

Forcing them as one of the other types has no effect.

I’m available for any testing you may need.

**Comment by keybuk** [comment]
If you add:

```
forceHorizontalShades: [ 44415 ]
```

to your `config.json`, what happens when you adjust the tilt (it's in Details on the iPhone UI)

**Comment by acolomba** [comment]
That works just fine. I must have made a mistake when I tested it earlier.

Thank you!

**Comment by keybuk** [comment]
I assume that nothing happens when you use the primary control, and only the secondary control under Details works?

**Comment by khit** [comment]
Hi! I just got some Powerview blinds which are called "Everwood" and are also horizontal slats/vanes (wood) but don't have motorized lift. But the log shows `Unknown type 40` instead of 39. I figured I'd just add to this open Issue, but let me know if you want me to move it to a new issue. Using `forceHorizontalShades` in the Homebridge `config.json` file works fine for these shades.

Thanks for a great plugin!

**Comment by keybuk** [comment]
@khit either is fine, it seems so far that a new type is allocated for even variations of color

**Comment by acolomba** [comment]
Errata in my earlier report. The correct setting for my parkland non-lifting blinds (39) is ```forceVerticalShades: [ 44415 ]```, not horizontal.

Their range is -90 to 90, not 0 to 90.

**Comment by khit** [comment]
For non-motorized lift blinds like mine - where tilt is the only function - would it be possible to make the Primary slider control tilt instead of having to click through to the Secondary slider in Settings for each device? It would allow make things a little easier/quicker in the Home.app UI and control accessible via Siri (I think). Right now the Primary sliders are all unused for me. Let me know if you want me to break this out into a separate issue. Thanks!

**Comment by keybuk** [comment]
@khit unfortunately that's completely up to the UI - the Apple Home app will always place a primary slider for the opening, and hide the tilt as a secondary slider in Details - other alternate apps have different UIs

**Comment by keybuk** [comment]
I recommend using the new built-in HomeKit support
